// Build-time configuration. The real `build_config.js` is generated by
// wscript from environment variables; this example shows the shape.
// Empty strings = proxy not configured -> demo mode.
module.exports = {
  PROXY_API_BASE: '',
  PROXY_SECRET: '',
};
